name: SpellingWizard
description: An application to help English learners.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  csv: ^4.0.3
  assets_audio_player: ^2.0.13+1
  tuple: ^1.0.3
  flutter_rating_bar: ^3.0.1+1
  step_progress_indicator: ^0.2.4+7
  path_provider: ^1.6.18
  sleek_circular_slider : ^1.1.0
  flip_card: ^0.4.4
  flutter_svg: ^0.19.1
  flutter_icons: ^1.1.0
  url_launcher: ^5.7.10
  flutter_colorpicker: ^0.3.4
  auto_size_text: ^2.1.0
  shimmer: ^1.1.2
  built_in_keyboard:
    git:
      url: https://github.com/Open-Segmentation-Systems/BuiltInKeyboard.git
      ref: main
  splashscreen:
    git:
      url: https://github.com/KarimMohamed20/SplashScreenFlutterPackage
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.8.1"

flutter_native_splash:
    image: assets/splash_icon.png
    color: "4A148C"
    android_disable_fullscreen: true

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Heavy.ttf
          weight: 900
        - asset: fonts/Raleway-Regular.ttf
          weight: 100
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Bold.otf
          weight: 900
        - asset: fonts/WorkSans-SemiBold.otf
          weight: 100
  
  assets:
    - assets/
    - assets/categories/Verbs_words/
    - assets/categories/Tools_words/
    - assets/categories/Animals_words/
    - assets/categories/Abstract_words/
    - assets/categories/Family_words/
    - assets/categories/Household_words/
    - assets/wizard.png
    - assets/icon.png
    - assets/splash_icon.png
    - assets/avatar/
    - assets/audio/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
